### ISSUE TITLE
.htaccess in wp-content/wonolog directory is not compatible with mod_authz_core (Apache 2.3+)

### ISSUE THREAD

**Issue by chesio** [inpsyde/Wonolog#23]
Hi,

the subject says it all :-) It's a minor issue, but it's easy to make `.htaccess` compatible with newer Apache versions.

#### Version Information

* Apache 2.4 with [mod_authz_core](https://httpd.apache.org/docs/trunk/mod/mod_authz_core.html) enabled

#### Steps to Reproduce

1. Browse the website, trigger generation of `wp-content/wonolog/` directory with `.htaccess` file
1. Try to access `wp-content/wonolog/`

#### What I Expected

403 Forbidden page

#### What Happened Instead

500 Internal Server Error page

#### How to fix

```
<IfModule mod_authz_core.c>
	Require all denied
</IfModule>
<IfModule !mod_authz_core.c>
	Deny from all
</IfModule>
```

**Comment by tfrommen** [comment]
Closed with 41a02f0e192bfef3f8d73528ee3e4eb9e3ccba9f.

**Comment by chesio** [comment]
Thanks!

**Comment by tfrommen** [comment]
Thank **you** for making us aware, and providing the fix right away. 🙂

**Comment by chesio** [comment]
Gerne! 😄
