### ISSUE TITLE
WANT TO USE WONOLOG FOR PLUGIN ERROR LOG ALSO SEND EMAIL ERROR

### ISSUE THREAD

**Issue by sharazghouri** [inpsyde/Wonolog#27]
#### Version Information

* PHP: 5.6
* WordPress: 4.8.3

#### Steps to Reproduce

1. 
1. 
1. 

#### What I Expected
WANT TO USE WONOLOG FOR PLUGIN ERROR LOG ALSO SEND EMAIL ERROR

**Comment by gmazzap** [comment]
Hi,

as explained in the docs (https://inpsyde.github.io/Wonolog/), Wonolog depends on [Monolog](https://github.com/Seldaek/monolog) which provides different ["handlers"](https://github.com/Seldaek/monolog/blob/master/doc/02-handlers-formatters-processors.md) for logging, among them there are several handlers that send emails:

- **"NativeMailerHandler"**, see https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/NativeMailerHandler.php
- **"MandrillHandler"**, see https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/MandrillHandler.php
- **"SendGridHandler"**, see https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/SendGridHandler.php
- **"SwiftMailerHandler"**, see https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/SwiftMailerHandler.php

Wonolog documentation (see https://inpsyde.github.io/Wonolog/docs/05-wonolog-customization.html#adding-handlers) explains how to use and configure Monolog handlers for Wonolog.

Moreover, recently "Torque" magazine published a in-depth article about Wonolog, that also explains how to use it with different Monolog handlers, you can find it here: https://torquemag.io/2017/10/logging-wordpress-bugs-wonolog/

Hope this helps.
