### ISSUE TITLE
Question: How to set log level

### ISSUE THREAD

**Issue by rmurillo21** [inpsyde/Wonolog#30]
Greetings - 

Can you advise how to set the minimum level for the default handler at bootstrap time?  I am getting DEBUG.DEBUG level messages and I only want DEBUG.INFO.

Thanks!

**Comment by gmazzap** [comment]
Hi,
you can either use `WONOLOG_DEFAULT_MIN_LEVEL` environment variable (see https://inpsyde.github.io/Wonolog/docs/03-a-deeper-look-at-wonolog.html#default-handler-minimum-log-level) or you can customize the default handler on bootstrap (see https://inpsyde.github.io/Wonolog/docs/05-wonolog-customization.html#customizing-the-default-handler).

**Comment by rmurillo21** [comment]
Perfect thanks
