### ISSUE TITLE
PHP Fatal error:  Interface 'Psr\Log\LoggerInterface' 

### ISSUE THREAD

**Issue by rmurillo21** [inpsyde/Wonolog#31]
Hello,

I had installed and tested Wonolog on a local vagrant machine running Ubuntu 14.04 LTS. I used composer to install. Works great.

After commiting to repo and deploying the code to a test platform, I get:

PHP Fatal error:  Interface 'Psr\Log\LoggerInterface' not found in /var/wordpress/htdocs/vendor/monolog/monolog/src/Monolog/Logger.php on line 27

Note that Composer was not on that machine; I installed it, ran `composer install` 

Any suggestions?
Thanks in advance

**Comment by gmazzap** [comment]
It seems that composer dependencies are not installed properly on the machine where wonolog is used. Can you chech that:
- the `/vendor` folder exists
- it contains the folder `psr/log` folder
- composer autoload is loaded somewhere early, e.g. in `wp-config.php` file if you used composer to install the whole website via composer

**Comment by rmurillo21** [comment]
Found the issue. Had a `/log` in a .gitignore file in an upper folder. Thanks for the help.
