### ISSUE TITLE
Configuring arbitrary log paths

### ISSUE THREAD

**Issue by rmurillo21** [inpsyde/Wonolog#32]
I see that Wonolog uses dates in constructing a file path for its file log:

eg: `wonolog/2018/02/06.log`

Due to system preferences here, we want an arbitrary path eg wonolog/system.log

Can you suggest how I could configure this?

Thanks!

**Comment by gmazzap** [comment]
Wonolog default handler is date based.

The environment variable `WONOLOG_DEFAULT_HANDLER_ROOT_DIR` allows you to change the target directory and there are 2 filters that allow you to change the date format, and how it is used to compose the file name. They are: `wonolog.default-handler-filename` and `wonolog.default-handler-date-format` (see https://inpsyde.github.io/Wonolog/docs/05-wonolog-customization.html#default-handler-filter-hooks).

But still the file name must be date-based.

---

If you want to have a filename that is not data-based, best option is to replace the default handler. That's quite easy.

The first argument of `bootstrap()` function can be a [Monolog handler](https://github.com/Seldaek/monolog/blob/master/doc/02-handlers-formatters-processors.md#handlers) that will be used by Wonolog as its default handler:

```php
Inpsyde\Wonolog\bootstrap(new Monolog\Handler\StreamHandler('/path/to/system.log'));
```

(see https://inpsyde.github.io/Wonolog/docs/05-wonolog-customization.html#replacing-the-default-handler).

----

You can have a look at Monolog documentation (https://github.com/Seldaek/monolog#documentation) to know more about available handlers and how to use them.

I also suggest you to have a look at Wonolog documentation (https://github.com/inpsyde/Wonolog/tree/master/docs) that contains quite a lot info about this and other topics.

**Comment by rmurillo21** [comment]
Thank you!
