### ISSUE TITLE
How to setup greylog with wonolog?

### ISSUE THREAD

**Issue by juslintek** [inpsyde/Wonolog#37]
Hi, how to setup wonolog with greylog?

**Comment by Chrico** [comment]
Howdy. 

Basically you just need to use the [gelf-php](https://github.com/bzikarsky/gelf-php)-package. 

Have a look at: https://inpsyde.com/blog/logmanagement-mit-graylog/ :)

**Comment by drzraf** [comment]
I'm currently setting up wonolog with GrayLog. But I need to pass a custom field to the Gelf JSON payload aka an [additional](https://github.com/bzikarsky/gelf-php/blob/14b87aa31880b9f2da6de053674ea1e12d4a174b/src/Gelf/Message.php#L257)

These could be passed as the 3rd `array $context` argument of a [Gelf\Logger](https://github.com/bzikarsky/gelf-php/blob/8863061c21a4a53999d6f803c8ca16ed137bde31/src/Gelf/Logger.php#L51)

By default Wonolog initializes a [Monolog\Logger](https://github.com/inpsyde/Wonolog/blob/master/src/Channels.php#L132) using one parameter.
What would be the way to initialize the default context of a GelfHandler?

**Comment by Chrico** [comment]
Good morning.

Internally we're using the `Monolog\Logger`. The linked `Gelf\Logger` is not used in Wonolog by default. 

It is possible to use the `Inpsyde\Wonolog\Channels::ACTION_LOGGER`-hook, to replace the Logger, but it is currently not supported to use a `Psr\Log\LoggerInterface` here. Our code relies on `Logger::getName()` which is specific to Monolog.

When looking at the `Gelf\Message::$additionals`, i can see, that they are just added via `$message['_'.$key]`  in [`Message::toArray()`](https://github.com/bzikarsky/gelf-php/blob/14b87aa31880b9f2da6de053674ea1e12d4a174b/src/Gelf/Message.php#L298-L300).

What i would suggest is, that you bootstrap Wonolog with build in the GelfHandler and adding a processor to add the key:

```php
<?php
use Monolog\Handler\GelfHandler;
use Monolog\Processor ProcessorInterface;

$publisher = Gelf\Publisher();

$handler = new GelfHandler($publisher);
$handler->pushProcessor(new class implements ProcessorInterface {

    public function __invoke(array $record) 
    {
        $record['_your-token'] = '....';

        return $record;
    }
});

Wonolog\bootstrap($handler);

**Comment by gmazzap** [comment]
Wonolog v1 does not allow to use custom _Loggers_, but only custom _Handlers_ and/or _Formatters_. 

Wonolog v2 will have that possibility. As for v1, the solution provided by @Chrico is one way to go.

Alternatively, you could extend the [`GelfMessageFormatter`](https://github.com/Seldaek/monolog/blob/main/src/Monolog/Formatter/GelfMessageFormatter.php) like:

```php
class MyFormatter extends \Monolog\Formatter\GelfMessageFormatter
{
    private $token;

    public function __construct(
        string $token,
        ?string $systemName = null,
        ?string $extraPrefix = null,
        string $contextPrefix = 'ctxt_',
        ?int $maxLength = null
    ) {
        $this->token = $token;
        parent::__construct($systemName, $extraPrefix, $contextPrefix, $maxLength);
    }

    public function format(array $record): \Gelf\Message
    {
        $message = parent::format($record);

        return $message->setAdditional('token', $this->token);
    }
}
```

and then for Wonolog:

```php
$handler = new GelfHandler(new Gelf\Publisher());
$handler->setFormatter(new MyFormatter('...token...'));
Wonolog\bootstrap($handler);
```
