### ISSUE TITLE
Monolog 2.0.0 breaks compatability with Wonolog custom handlers.

### ISSUE THREAD

**Issue by michaelbragg** [inpsyde/Wonolog#43]
Monolog has just released version 2.0. As Wonolog pulles the latest stable version on monolog. the breaking changes in v2 look to break custom handlers used in Wonolog.

#### Version Information

* PHP: 7.2.*
* WordPress: 5.2.2

#### Steps to Reproduce

1. Standard WordPress setup
1. Wonolog installed as per readme
1. Add custom handler:
```
use Inpsyde\Wonolog;
use Monolog\Handler\NativeMailerHandler;
use Monolog\Handler\SlackWebhookHandler;
use Monolog\Handler\StreamHandler;
use Monolog\Formatter\LineFormatter;
use Monolog\Logger;

/**
 * Add email handler.
 */
$email_handler = new NativeMailerHandler(
	'test@example.com',        // to
	'Security alert from example.com', // subject
	'wordpress@example.com',    // from
	Logger::ERROR                      // minimum level
);

Inpsyde\Wonolog\bootstrap()
  ->use_handler( $email_handler );
```

#### What I Expected

Website to load as standard.

#### What Happened Instead

> The site is experiencing technical difficulties.

Remove the custom handler and the site works ask expected. Just without the functionality of a custom handler.

**Comment by gmazzap** [comment]
Fixed via #44 thanks to @pierre-dargham 

I've also released v1.0.3.
