### ISSUE TITLE
Errors not appearing on sematext/Raygun

### ISSUE THREAD

**Issue by Rahe** [inpsyde/Wonolog#45]
#### Version Information

* PHP: 7.3
* WordPress: latest

#### Steps to Reproduce

1. Add a service provider like sematext or Raygun
2. Push errors through do_action
3. Nothing appears
4. Use a SyslogUdpHandler
5. Push errors through without wonolog do_action
6. Something appears

When do not add any external handler everything appears on the files.

#### What I Expected
I espected that the WordPres internal errors and my custom log errors appears on the service.
Now I only have the wonolog basic errors.

#### What Happened Instead
Nothing is pushed to the web service.

If I'm using directly Monolog with SyslogUdpHandler, every data is pushed to sematext.
I am missing something ?

**Comment by gmazzap** [comment]
Hi Rahe,

at Inpsyde we are usieng Wonolog with different 3rd party services, so I can confirm with 100% security that Monolog can work with external services.

Regarding the reason why it does not work for you I can't say much without more details, and without seeing how you are integrating those.

**Comment by Rahe** [comment]
Hello,

The problem is, this is working with Monolog standalone, right i'm passing through Wonolog nothing appears.

Is there a way to debug this ?

**Comment by gmazzap** [comment]
Do you have some code to show? Honestly, I've no way to understand where the problem could be. I _suspect_ I might have to do with log levels setting for Wonolog, but without further details, it is no more than a wild guess.

**Comment by Rahe** [comment]
Hello, the contant WP_DEBUG_LOG was at false, then nothing where send ;(
Now events are added to sematext thank you :)
