### ISSUE TITLE
Support for audit/logging plugins

### ISSUE THREAD

**Issue by strarsis** [inpsyde/Wonolog#46]
[Stream](https://github.com/xwp/stream) and [WP Security Audit Log](https://github.com/WPWhiteSecurity/WP-Security-Audit-Log) plugin offer some functions for adding new logs. Monolog could nicely integrate by calling their functions for logging, probably in a handler?
Currently, I would have to add invocations for these two plugins and monolog.

Related issues:
https://github.com/WPWhiteSecurity/WP-Security-Audit-Log/issues/499
https://github.com/xwp/stream/issues/1040

**Comment by Chrico** [comment]
We would suggest to build custom extensions which are build on top of Wonolog. We're already doing this internally with Logz.io integration https://github.com/inpsyde/logzio-monolog internally. But we'll support an easier API to listen to Plugins in version 2.
