### ISSUE TITLE
[2.x] Q&A improvments

### ISSUE THREAD

**Issue by Chrico** [inpsyde/Wonolog#52]
We need to do following for version 2.x of Wonolog:

- Add Github Actions
- Add PSALM
- Add Inpsyde Coding Standards 1.x

All tests should pass, which also contains renaming methods and adding return types.

Minimum PHP version will be 7.2 because Monolog requires this as version.

**Comment by Chrico** [comment]
Starting to work with 9f5aa71 and e8ae174  on it.

**Comment by szepeviktor** [comment]
Continued working on it #53

**Comment by gmazzap** [comment]
This is all done in `2.x` branch:

- Github action for static QA (PHPCS & Psalm) + Unit tests in the same workflow (2 separate jobs): https://github.com/inpsyde/Wonolog/blob/2.x/.github/workflows/qa.yml
- Github action for integration tests (running in Docker with full WP installation): https://github.com/inpsyde/Wonolog/blob/2.x/.github/workflows/integration-tests.yml
- Psalm config: https://github.com/inpsyde/Wonolog/blob/2.x/psalm.xml
- PHPCS config with Inpsyde CS: https://github.com/inpsyde/Wonolog/blob/2.x/phpcs.xml.dist
- Min PHP ver is 7.2 https://github.com/inpsyde/Wonolog/blob/2.x/composer.json#L31 and we're running tests on versions from 7.2 to 8.0 https://github.com/inpsyde/Wonolog/blob/2.x/.github/workflows/qa.yml#L43
- Tests are green and we've a good coverage: https://github.com/inpsyde/Wonolog/actions/runs/1466660872 (coverage report downloadable as HTML from action artifact)
- Pretty much all methods have type declarations, the `phpcs:disable` is reduced to the very minimum

So I guess we can close this. I would like to release a "beta" version of v2 soon.
