### ISSUE TITLE
Log to custom channel

### ISSUE THREAD

**Issue by ericosullivanwp** [inpsyde/Wonolog#64]
**Is your feature request related to a problem? Please describe.**
I'm trying to configure a custom logging channel so that the logs from our plugin can be easily distinguished from log records from other plugins that may be using wonolog.

**Describe the solution you'd like**
A way to set a custom channel that we can log to. Looking at the code in Channels.php, it raises an exception if a channel is specified that the comoponent is unaware of which implies, that it should be possible to add more known channels.

**Describe alternatives you've considered**
We can simply create a wrapper for our plugin that prefixes all log records with a custom string but this feels like a cludge given teh level of customizable features in other aspects of Wonolog.

**Comment by gmazzap** [comment]
Ho @ericosullivanwp 

In **v1**, you have to manually register the channel first via the `wonolog.channels` filter. See an usage example here: https://github.com/inpsyde/Wonolog/blob/master/docs/06-custom-hook-listeners.md#integrating-a-custom-listener

in **v2** there's this: https://github.com/inpsyde/Wonolog/blob/2.x/docs/09-configuration-cheat-sheet.md#channels-configuration
but as written there that is rarely needed.
